services:
  chamados:
    build: .
    container_name: chamados
    ports:
      - "8000:80"
    depends_on:
      - mariadb
    networks:
      - chamados-network
    volumes:
      - ./:/var/www/html
    environment:
      HOME: /tmp
    user: "${UID:-1000}:${GID:-1000}"

  mariadb:
    image: mariadb:11
    container_name: chamados_mariadb
    restart: always
    environment:
      MYSQL_DATABASE: chamados
      MYSQL_USER: chamados
      MYSQL_PASSWORD: chamados
      MYSQL_ROOT_PASSWORD: chamados
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - chamados-network

  selenium:
    image: selenium/standalone-chrome
    container_name: chamados_selenium
    ports:
      - "7900:7900" # VNC (pra ver o browser rodando)
    networks:
      - chamados-network
    shm_size: 2gb

networks:
  chamados-network:

volumes:
  mariadb_data: